-- Disable RLS for local development
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.renewals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_properties DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.renewal_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.renewal_workflow_outcomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.key_dates DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts DISABLE ROW LEVEL SECURITY; 