import { createClient } from '@/lib/supabase/server';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { GenerateInviteButton } from './GenerateInviteButton';

export default async function AdminInvitesPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  
  if (!user) redirect('/login');
  
  const { data: profile } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', user.id)
    .single();
  
  if (!profile || !['admin', 'ambassador'].includes(profile.user_role)) {
    redirect('/members');
  }

  const { data: inviteCodes } = await supabase
    .from('invite_codes')
    .select('*, generated_by_profile:profiles!invite_codes_generated_by_fkey(name, email), used_by_profile:profiles!invite_codes_used_by_fkey(name, email)')
    .order('created_at', { ascending: false });

  const activeCount = inviteCodes?.filter(c => c.is_active && !c.used_by).length || 0;
  const usedCount = inviteCodes?.filter(c => c.used_by).length || 0;

  return (
    <div className="min-h-screen">
      <nav className="fixed top-0 w-full z-50 bg-background/80 backdrop-blur-sm border-b border-neon-purple/20">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <Link href="/admin" className="font-mono text-2xl font-bold">
            <span className="neon-purple">GOOD_HANG</span>
            <span className="text-neon-cyan text-sm ml-2">ADMIN</span>
          </Link>
          <div className="flex gap-6 items-center">
            <Link href="/admin" className="text-foreground hover:text-neon-cyan transition-colors font-mono">Dashboard</Link>
            <Link href="/members" className="text-foreground hover:text-neon-cyan transition-colors font-mono">Members</Link>
            <form action="/auth/signout" method="post">
              <button className="text-foreground-dim hover:text-neon-magenta transition-colors font-mono">Sign Out</button>
            </form>
          </div>
        </div>
      </nav>

      <main className="container mx-auto px-6 pt-32 pb-20">
        <div className="max-w-7xl mx-auto">
          <div className="mb-12 flex justify-between items-start">
            <div>
              <h1 className="text-5xl font-bold font-mono neon-cyan mb-4">INVITE CODES</h1>
              <p className="text-foreground-dim font-mono text-lg">Generate and manage member invite codes</p>
            </div>
            <GenerateInviteButton userId={user.id} />
          </div>

          <div className="grid md:grid-cols-3 gap-6 mb-12">
            <div className="border-2 border-neon-cyan/30 bg-background-lighter p-6">
              <div className="text-4xl font-bold font-mono neon-cyan mb-2">{inviteCodes?.length || 0}</div>
              <div className="text-foreground-dim font-mono text-sm uppercase">Total Codes</div>
            </div>
            <div className="border-2 border-green-500/30 bg-background-lighter p-6">
              <div className="text-4xl font-bold font-mono text-green-400 mb-2">{activeCount}</div>
              <div className="text-foreground-dim font-mono text-sm uppercase">Active</div>
            </div>
            <div className="border-2 border-neon-purple/30 bg-background-lighter p-6">
              <div className="text-4xl font-bold font-mono neon-purple mb-2">{usedCount}</div>
              <div className="text-foreground-dim font-mono text-sm uppercase">Used</div>
            </div>
          </div>

          <div className="border-2 border-neon-cyan/30 bg-background-lighter p-6">
            <h2 className="text-2xl font-bold font-mono neon-cyan mb-6">ALL CODES</h2>
            <div className="overflow-x-auto">
              <table className="w-full font-mono text-sm">
                <thead>
                  <tr className="border-b border-neon-cyan/20">
                    <th className="text-left py-3 text-foreground-dim">Code</th>
                    <th className="text-left py-3 text-foreground-dim">Status</th>
                    <th className="text-left py-3 text-foreground-dim">Generated By</th>
                    <th className="text-left py-3 text-foreground-dim">Used By</th>
                    <th className="text-left py-3 text-foreground-dim">Created</th>
                  </tr>
                </thead>
                <tbody>
                  {inviteCodes && inviteCodes.length > 0 ? (
                    inviteCodes.map((code: { id: string; code: string; is_active: boolean; used_by: string | null; generated_by_profile: { name: string; email: string } | null; used_by_profile: { name: string; email: string } | null; created_at: string }) => (
                      <tr key={code.id} className="border-b border-foreground-dim/10">
                        <td className="py-3 text-foreground font-bold">{code.code}</td>
                        <td className="py-3">
                          <span className={code.is_active && !code.used_by ? 'text-green-400' : code.used_by ? 'text-neon-purple' : 'text-foreground-dim'}>
                            {code.is_active && !code.used_by ? 'Active' : code.used_by ? 'Used' : 'Inactive'}
                          </span>
                        </td>
                        <td className="py-3 text-foreground-dim">{code.generated_by_profile?.name || '-'}</td>
                        <td className="py-3 text-foreground-dim">{code.used_by_profile?.name || '-'}</td>
                        <td className="py-3 text-foreground-dim">{new Date(code.created_at).toLocaleDateString()}</td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={5} className="py-8 text-center text-foreground-dim">No invite codes yet. Generate one to get started!</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
