/**
 * Greeting Slide - Common across all workflows
 *
 * Purpose: Introduce the workflow and get user buy-in to proceed
 *
 * Reusable across:
 * - All workflow types (risk, opportunity, strategic, renewal)
 * - Different urgency levels
 * - Different workflow purposes
 *
 * Context Variables:
 * - purpose: 'executive_departure', 'renewal_preparation', 'expansion_opportunity', etc.
 * - urgency: Affects tone and button colors
 * - custom_message: Override default greeting
 */

import {
  SlideBuilder,
  SlideDefinition,
  SlideContext,
  createSlideBuilder,
  applyContextVariables,
  COMMON_PLACEHOLDERS,
} from '../baseSlide';

// Default greeting templates (fallbacks only - prefer context.variables.greetingText)
// In production, these would typically be generated by LLM based on customer context
const GREETING_TEMPLATES = {
  executive_departure: "{{departed_contact.name}} has left {{customer.name}}. Let's maintain our relationship strength.",
  renewal_preparation: "{{customer.name}}'s renewal is coming up. Let's prepare a strategic plan.",
  expansion_opportunity: "Expansion opportunity at {{customer.name}}. Let's explore!",
  account_review: "Time for {{customer.name}}'s account review.",
  churn_risk: "{{customer.name}} is showing churn risk signs. Let's address proactively.",
  default: "Let's work on {{customer.name}}.",
};

const URGENCY_CONFIG = {
  critical: {
    buttonColor: 'bg-red-600',
    buttonText: 'Address Now',
    tone: 'urgent',
  },
  high: {
    buttonColor: 'bg-orange-600',
    buttonText: 'Start Planning',
    tone: 'important',
  },
  medium: {
    buttonColor: 'bg-blue-600',
    buttonText: 'Let\'s Begin',
    tone: 'collaborative',
  },
  low: {
    buttonColor: 'bg-blue-600',
    buttonText: 'Review',
    tone: 'casual',
  },
};

/**
 * Default checklist items by workflow purpose
 */
const DEFAULT_CHECKLIST_ITEMS: Record<string, string[]> = {
  renewal_preparation: [
    'Review account health and contract details',
    'Analyze current pricing vs. market benchmarks',
    'Identify expansion opportunities',
    'Prepare renewal quote',
    'Create action plan and next steps',
  ],
  executive_departure: [
    'Assess impact of departure on relationship',
    'Identify replacement contacts',
    'Draft outreach communication',
    'Update stakeholder map',
    'Create follow-up plan',
  ],
  expansion_opportunity: [
    'Review current usage and adoption',
    'Identify expansion opportunities',
    'Prepare business case',
    'Draft expansion proposal',
    'Plan stakeholder engagement',
  ],
  churn_risk: [
    'Analyze risk indicators',
    'Identify root causes',
    'Plan recovery strategy',
    'Prepare value demonstration',
    'Create action plan',
  ],
  account_review: [
    'Review account health metrics',
    'Analyze usage patterns',
    'Identify opportunities and risks',
    'Update success plan',
    'Define next steps',
  ],
  default: [
    'Review current situation',
    'Analyze key factors',
    'Develop recommendations',
    'Create action plan',
    'Define next steps',
  ],
};

export const greetingSlide: SlideBuilder = createSlideBuilder(
  {
    id: 'greeting',
    name: 'Workflow Introduction',
    category: 'common',
    description: 'Greet user and get buy-in to proceed with workflow',
    estimatedMinutes: 1,
    requiredFields: ['customer.name'],
    optionalFields: [
      'customer.renewal_date',
      'customer.utilization',
      'departed_contact.name',
      'workflow.estimated_minutes',
    ],
    tags: ['intro', 'greeting', 'start'],
    version: '1.0.0',
  },
  (context?: SlideContext) => {
    const purpose = context?.purpose || 'default';
    const urgency = context?.urgency || 'medium';
    const urgencyConfig = URGENCY_CONFIG[urgency];

    // Select greeting message based on purpose
    // Priority: custom greetingText > custom_message > purpose-based template > default
    // In production, greetingText should come from LLM based on customer analysis
    let greetingText = context?.variables?.greetingText
      || context?.variables?.custom_message
      || GREETING_TEMPLATES[purpose as keyof typeof GREETING_TEMPLATES]
      || GREETING_TEMPLATES.default;

    // Apply context variables (hydrate placeholders)
    greetingText = applyContextVariables(greetingText, context);

    // Allow custom buttons from context, otherwise use defaults
    const buttons = context?.variables?.buttons || [
      {
        label: urgencyConfig.buttonText,
        value: 'start',
        'label-background': urgencyConfig.buttonColor,
        'label-text': 'text-white'
      },
      {
        label: 'Snooze',
        value: 'snooze',
        'label-background': 'bg-gray-500',
        'label-text': 'text-white'
      },
    ];

    return {
      id: 'greeting',
      title: context?.overrides?.title || 'Today\'s Critical Task',
      description: context?.overrides?.description || 'Introduction and workflow kickoff',
      label: 'Start',
      stepMapping: 'greeting',

      chat: {
        // Enable LLM-generated greeting when INTEL is available
        generateInitialMessage: context?.variables?.enableLLMGreeting !== false,
        initialMessage: {
          text: greetingText, // Fallback if LLM generation fails
          buttons,
          nextBranches: {
            'start': 'proceed',
            // 'snooze' removed - will fall through to handleButtonClick which opens EnhancedSnoozeModal
          }
        },
        branches: {
          'proceed': {
            response: "Great! Let's dive in.",
            actions: ['nextSlide']
          },
          // 'handle-snooze' branch removed - snooze is now handled by handleButtonClick → handleSnooze
        }
      },

      artifacts: {
        sections: context?.variables?.showPlanningChecklist === false ? [] : [
          {
            id: 'planning-checklist',
            title: context?.variables?.checklistTitle || 'Planning Checklist',
            type: 'custom',
            visible: true,
            data: {
              componentType: 'PlanningChecklistArtifact',
              props: {
                title: context?.variables?.checklistTitle || "Here's what we'll accomplish together:",
                items: buildChecklistItems(context),
                showActions: false
              }
            }
          }
        ]
      }
    };
  }
);

/**
 * Build checklist items from slide sequence or explicit checklistItems
 *
 * Priority:
 * 1. Explicit checklistItems from context (for backward compatibility)
 * 2. Auto-generated from slideSequence using each slide's checklistTitle
 * 3. Fallback to default items based on purpose
 */
function buildChecklistItems(context?: SlideContext): Array<{ id: string; label: string; completed: boolean }> {
  // Priority 1: Explicit checklistItems
  const explicitItems = context?.variables?.checklistItems;
  if (explicitItems && Array.isArray(explicitItems) && explicitItems.length > 0) {
    return explicitItems.map((label: string, index: number) => ({
      id: `${index + 1}`,
      label,
      completed: false
    }));
  }

  // Priority 2: Build from slideSequence + slideLibrary
  const slideSequence = context?.variables?.slideSequence;
  const slideLibrary = context?.variables?.slideLibrary;

  if (slideSequence && Array.isArray(slideSequence) && slideLibrary) {
    const items: Array<{ id: string; label: string; completed: boolean }> = [];

    for (let i = 0; i < slideSequence.length; i++) {
      const slideId = slideSequence[i];

      // Skip greeting and summary slides in the checklist
      if (slideId === 'greeting' || slideId.includes('summary')) {
        continue;
      }

      const slideBuilder = slideLibrary[slideId];
      if (slideBuilder) {
        // Call the slide builder to get its definition
        const slideDef = slideBuilder();
        // Get checklistTitle from the slide definition
        const checklistTitle = slideDef.checklistTitle
          || slideDef.name
          || slideDef.structure?.title
          || slideId.replace(/-/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase());

        items.push({
          id: `${items.length + 1}`,
          label: checklistTitle,
          completed: false
        });
      }
    }

    if (items.length > 0) {
      return items;
    }
  }

  // Priority 3: Fallback to default items based on purpose
  const purpose = context?.purpose || 'default';
  const defaultItems = DEFAULT_CHECKLIST_ITEMS[purpose as keyof typeof DEFAULT_CHECKLIST_ITEMS]
    || DEFAULT_CHECKLIST_ITEMS.default;

  return defaultItems.map((label: string, index: number) => ({
    id: `${index + 1}`,
    label,
    completed: false
  }));
}
