/**
 * Recommendation Type Taxonomy
 *
 * Defines the structured taxonomy of recommendation types that can be
 * generated by workflows. Each recommendation type specifies which workflows
 * can generate it, what actions it supports, and what data is required.
 */

export type RecommendationCategory =
  | 'FEATURE_ADOPTION'
  | 'EXECUTIVE_ENGAGEMENT'
  | 'PRICING_STRATEGY'
  | 'PROCEDURAL';

export type RecommendationSubcategory =
  // FEATURE_ADOPTION subcategories
  | 'new_feature_announcement'
  | 'underutilized_feature'
  | 'advanced_capability_intro'

  // EXECUTIVE_ENGAGEMENT subcategories
  | 'conversation_starters'
  | 'industry_insights'
  | 'product_roadmap_preview'
  | 'success_story_sharing'
  | 'relationship_building'
  | 'personal_touchpoint'
  | 'executive_alignment_call'
  | 'qbr_preparation'

  // PRICING_STRATEGY subcategories
  | 'usage_increase_justification'
  | 'value_realization_documentation'
  | 'expansion_opportunity_prep'

  // PROCEDURAL subcategories
  | 'renewal_timeline_awareness'
  | 'stakeholder_mapping_update'
  | 'contract_review_reminder';

export interface RecommendationTypeDefinition {
  category: RecommendationCategory;
  subcategory: RecommendationSubcategory;
  validWorkflows: string[]; // Which workflow stages can generate this type
  supportedActions: string[]; // Which action types this recommendation can trigger
  requiredData: string[]; // What data fields are needed to justify this recommendation
  description: string;
}

/**
 * Recommendation Type Registry
 * Maps each recommendation subcategory to its definition
 */
export const RecommendationTypeRegistry: Record<RecommendationSubcategory, RecommendationTypeDefinition> = {
  // FEATURE ADOPTION
  'new_feature_announcement': {
    category: 'FEATURE_ADOPTION',
    subcategory: 'new_feature_announcement',
    validWorkflows: ['monitor', 'prepare', 'engage'],
    supportedActions: ['send_email', 'schedule_meeting', 'skip', 'snooze'],
    requiredData: ['data.product.recentReleases', 'data.usage.featureAdoption'],
    description: 'Announce new features that align with customer usage patterns'
  },

  'underutilized_feature': {
    category: 'FEATURE_ADOPTION',
    subcategory: 'underutilized_feature',
    validWorkflows: ['monitor', 'prepare', 'engage'],
    supportedActions: ['send_email', 'schedule_meeting', 'review_data', 'skip', 'snooze'],
    requiredData: ['data.usage.featureAdoption', 'data.usage.utilizationRate'],
    description: 'Highlight paid features customer is not using effectively'
  },

  'advanced_capability_intro': {
    category: 'FEATURE_ADOPTION',
    subcategory: 'advanced_capability_intro',
    validWorkflows: ['monitor', 'prepare', 'engage', 'negotiate'],
    supportedActions: ['send_email', 'schedule_meeting', 'skip', 'snooze'],
    requiredData: ['data.usage.userSkillLevel', 'data.usage.featureAdoption'],
    description: 'Introduce advanced capabilities to mature users'
  },

  // EXECUTIVE ENGAGEMENT - Conversation Starters
  'conversation_starters': {
    category: 'EXECUTIVE_ENGAGEMENT',
    subcategory: 'conversation_starters',
    validWorkflows: ['monitor', 'prepare', 'engage'],
    supportedActions: ['review_data', 'get_transcript', 'skip', 'snooze'],
    requiredData: ['data.engagement.lastMeeting', 'intelligence.healthScore'],
    description: 'General talking points for next customer interaction'
  },

  'industry_insights': {
    category: 'EXECUTIVE_ENGAGEMENT',
    subcategory: 'industry_insights',
    validWorkflows: ['monitor', 'prepare', 'engage'],
    supportedActions: ['send_email', 'skip', 'snooze'],
    requiredData: ['customer.industry', 'data.market.trends'],
    description: 'Share relevant industry trends or benchmarks'
  },

  'product_roadmap_preview': {
    category: 'EXECUTIVE_ENGAGEMENT',
    subcategory: 'product_roadmap_preview',
    validWorkflows: ['prepare', 'engage', 'negotiate'],
    supportedActions: ['send_email', 'schedule_meeting', 'skip', 'snooze'],
    requiredData: ['data.product.roadmap', 'data.feedback.featureRequests'],
    description: 'Preview upcoming features aligned with customer requests'
  },

  'success_story_sharing': {
    category: 'EXECUTIVE_ENGAGEMENT',
    subcategory: 'success_story_sharing',
    validWorkflows: ['monitor', 'prepare', 'engage', 'negotiate'],
    supportedActions: ['send_email', 'skip', 'snooze'],
    requiredData: ['customer.industry', 'data.caseStudies'],
    description: 'Share relevant customer success stories'
  },

  // EXECUTIVE ENGAGEMENT - Relationship Building
  'relationship_building': {
    category: 'EXECUTIVE_ENGAGEMENT',
    subcategory: 'relationship_building',
    validWorkflows: ['monitor', 'prepare', 'engage'],
    supportedActions: ['send_email', 'schedule_meeting', 'skip', 'snooze'],
    requiredData: ['data.engagement.lastMeeting', 'data.salesforce.contacts'],
    description: 'General relationship building activities'
  },

  'personal_touchpoint': {
    category: 'EXECUTIVE_ENGAGEMENT',
    subcategory: 'personal_touchpoint',
    validWorkflows: ['monitor', 'prepare'],
    supportedActions: ['send_email', 'skip', 'snooze'],
    requiredData: ['data.salesforce.contacts', 'data.engagement.personalEvents'],
    description: 'Send card, congratulations, or personal acknowledgment'
  },

  'executive_alignment_call': {
    category: 'EXECUTIVE_ENGAGEMENT',
    subcategory: 'executive_alignment_call',
    validWorkflows: ['prepare', 'engage', 'negotiate'],
    supportedActions: ['schedule_meeting', 'skip', 'snooze'],
    requiredData: ['data.salesforce.contacts', 'customer.arr'],
    description: 'Schedule executive-level alignment call'
  },

  'qbr_preparation': {
    category: 'EXECUTIVE_ENGAGEMENT',
    subcategory: 'qbr_preparation',
    validWorkflows: ['prepare', 'engage'],
    supportedActions: ['review_data', 'schedule_meeting', 'skip', 'snooze'],
    requiredData: ['data.engagement.lastQBR', 'data.usage.metrics'],
    description: 'Prepare for upcoming Quarterly Business Review'
  },

  // PRICING STRATEGY
  'usage_increase_justification': {
    category: 'PRICING_STRATEGY',
    subcategory: 'usage_increase_justification',
    validWorkflows: ['monitor', 'prepare', 'engage', 'negotiate'],
    supportedActions: ['review_data', 'skip', 'snooze'],
    requiredData: ['data.usage.trend', 'data.usage.changePercent'],
    description: 'Document usage increases to justify price adjustments'
  },

  'value_realization_documentation': {
    category: 'PRICING_STRATEGY',
    subcategory: 'value_realization_documentation',
    validWorkflows: ['prepare', 'engage', 'negotiate'],
    supportedActions: ['review_data', 'update_crm', 'skip', 'snooze'],
    requiredData: ['data.usage.metrics', 'intelligence.valueScore'],
    description: 'Document ROI and value delivered for renewal discussions'
  },

  'expansion_opportunity_prep': {
    category: 'PRICING_STRATEGY',
    subcategory: 'expansion_opportunity_prep',
    validWorkflows: ['prepare', 'engage', 'negotiate'],
    supportedActions: ['review_data', 'schedule_meeting', 'skip', 'snooze'],
    requiredData: ['data.usage.utilizationRate', 'customer.arr'],
    description: 'Identify upsell or expansion opportunities'
  },

  // PROCEDURAL
  'renewal_timeline_awareness': {
    category: 'PROCEDURAL',
    subcategory: 'renewal_timeline_awareness',
    validWorkflows: ['prepare', 'engage', 'negotiate', 'finalize'],
    supportedActions: ['send_email', 'skip', 'snooze'],
    requiredData: ['customer.renewalDate', 'workflow.daysUntilRenewal'],
    description: 'Communicate renewal timeline and upcoming milestones'
  },

  'stakeholder_mapping_update': {
    category: 'PROCEDURAL',
    subcategory: 'stakeholder_mapping_update',
    validWorkflows: ['prepare', 'engage'],
    supportedActions: ['review_data', 'update_crm', 'skip', 'snooze'],
    requiredData: ['data.salesforce.contacts', 'data.engagement.stakeholderChanges'],
    description: 'Update stakeholder map with recent changes'
  },

  'contract_review_reminder': {
    category: 'PROCEDURAL',
    subcategory: 'contract_review_reminder',
    validWorkflows: ['finalize', 'signature'],
    supportedActions: ['send_email', 'skip', 'snooze'],
    requiredData: ['data.contractStatus', 'workflow.daysUntilRenewal'],
    description: 'Remind stakeholders to review contract terms'
  }
};

/**
 * Recommendation Data Structure
 * What the LLM generates for each recommendation
 */
export interface Recommendation {
  id: string;
  workflowId: string;
  customerId: string;

  // Classification
  category: RecommendationCategory;
  subcategory: RecommendationSubcategory;

  // Content
  title: string;
  description: string;
  rationale: string; // Why this recommendation matters

  // Supporting data
  dataPoints: DataPoint[];

  // Priority
  priorityScore: number; // 1-100, calculated from impact + urgency
  impact: 'low' | 'medium' | 'high';
  urgency: 'low' | 'medium' | 'high';

  // Actions
  suggestedActions: string[]; // Array of action IDs (from action-types.ts)

  // Metadata
  createdAt: Date;
  status: 'pending' | 'actioned' | 'skipped' | 'snoozed';
  snoozedUntil?: Date;
}

/**
 * Data Point
 * Individual pieces of evidence supporting a recommendation
 */
export interface DataPoint {
  label: string;
  value: string | number;
  context?: string; // Optional explanation
  source: string; // Where this data came from (e.g., 'data.usage.trend')
}

/**
 * Helper: Get valid recommendation types for a workflow stage
 */
export function getValidRecommendationTypes(workflowId: string): RecommendationTypeDefinition[] {
  return Object.values(RecommendationTypeRegistry).filter(
    def => def.validWorkflows.includes(workflowId)
  );
}

/**
 * Helper: Get supported actions for a recommendation type
 */
export function getSupportedActions(subcategory: RecommendationSubcategory): string[] {
  return RecommendationTypeRegistry[subcategory]?.supportedActions || [];
}
